require("core.setting")
require("core.keymaps")
require("core.plugins")

-- require("plugins.plugins-setup")
-- require("plugins.lualine")
-- require("plugins.bufferline")
-- require("plugins.nvim-tree")
-- require("plugins.telescope")
-- require("plugins.nvim-autopairs")
-- require("plugins.gitsigns")
-- require("plugins.dashboard")
